name: Reader tests


on: [pull_request, push]

# # Cancel actions when new commits are pushed to PR
# concurrency: 
#     group: ${{ github.head_ref }}
#     cancel-in-progress: true


jobs:
  test-python-reader:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [
          ubuntu-lastest,
          windows-latest,
          macos-11
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./python/[test]
          if [ -f python/requirements.txt ]; then pip install -r python/requirements.txt; fi

      - name: Tests
        run: |
          pytest --color=yes

